### ISSUE TITLE
get_sessions(start, end)

### ISSUE THREAD

**Issue by ghost** [giginet/beddit-python#1]
Hi, get_user and get_session methods worked for me, but when I call get_sessions i got this error:

Call:
client.get_sessions(start=start_date, end=end_date)
Error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pero/anaconda2/lib/python2.7/site-packages/beddit/client.py", line 15, in _is_logged_in
    return func(self, *args, **kwargs)
  File "/home/pero/anaconda2/lib/python2.7/site-packages/beddit/client.py", line 129, in get_sessions
    return [Session(session) for session in r.json()]
  File "/home/pero/anaconda2/lib/python2.7/site-packages/beddit/session.py", line 30, in __init__
    self.sampled_tracks = [SampledTrack(obj) for obj in response_object.get('sampled_tracks', [])]
  File "/home/pero/anaconda2/lib/python2.7/site-packages/beddit/session.py", line 14, in __init__
    self.samples_per_frame = obj['samples_per_frame']
TypeError: string indices must be integers

**Comment by giginet** [comment]
Hi, thank you for reporting the issue.

I'll try to fix it.
Please moment.

**Comment by ghost** [comment]
Hi :) I would like to ask you how soon can I expect the fix. 
Thank you for your response.

**Comment by giginet** [comment]
@peterrot 

I fixed this issue and deployed as 0.1.1.
It is available on PyPI.

Sorry for waiting you.

**Comment by peterrot** [comment]
Thank you very much. The method get_sessions now works fine, but the get_user() doesn't work anymore. The first one worked before. There are two calls below, one without parameters, and one with 1: 

>>> u = client.get_user()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "beddit/client.py", line 15, in _is_logged_in
    return func(self, *args, **kwargs)
  File "beddit/client.py", line 151, in get_user
    return User(r.json())
  File "beddit/user.py", line 18, in __init__
    self.weight = float(response_object['weight'])
TypeError: float() argument must be a string or a number


>>> u = client.get_user(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "beddit/client.py", line 15, in _is_logged_in
    return func(self, *args, **kwargs)
  File "beddit/client.py", line 153, in get_user
    raise BedditClient.APIError(r.json()['description'])
beddit.client.APIError: Permission denied

**Comment by giginet** [comment]
@peterrot Thank you for reporting the issue.

I apologize to make you inconvenience.
I'll fix this ASAP.

**Comment by peterrot** [comment]
Hi,
I would like to ask you if that usage of a function is supposed to be right?

u = client.get_user()
print u.id
print u.email
print u.name
print u.date_of_birth
print u.sex
print u.weight
print u.height
print u.sleep_time_goal
print u.tip_audiences
print u.created
print u.updated

**Comment by ghost** [comment]
Now I found the error - just add additional if statements to check if parameters do actually exist in User  __init__ function, before you assign them (in my case those parameters like response_object["weight"] and response_object["height"] were not defined), so you can just add if like this:

if response_object['weight']:
      self.weight = float(response_object['weight'])
if response_object['height']:
      self.height = float(response_object['height'])

or something similar..

Thank you very much ;)

**Comment by giginet** [comment]
@peterrot 
Sorry for my late reply.

I checked your situation.
It seems to work correctly.

```
beddit.client.APIError: Permission denied
```

You can only get the user information of yours or you permitted to access.
You seem not to have permission to access user `1`.

See this documentation for detail.
https://github.com/beddit/beddit-api/blob/master/3_1-UserResources.md

If you'd like to get your own profile, you don't pass the `user_id` argument.

```python
import os
from beddit.client import BedditClient

client = BedditClient(os.environ.get('BEDDIT_USERNAME'), os.environ.get('BEDDIT_PASSWORD'))

user = client.get_user()
print(user.name)
print(user.height)
print(user.weight)
```
